# Generated by Django 5.1 on 2024-09-04 19:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_rename_first_name_user_name_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_text', models.CharField(max_length=100, verbose_name='Ошибка')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2024, 9, 4, 19, 58, 2, 413484, tzinfo=datetime.timezone.utc), verbose_name='Дата и время ошибки')),
            ],
        ),
    ]
